// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://htzapqbpojigdfmarmcy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh0emFwcWJwb2ppZ2RmbWFybWN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1ODIzNTYsImV4cCI6MjA2MTE1ODM1Nn0.Ec6MBk3iu1VcQp_9ARVwpKERbeM6Bcp_JQN1FfhUuLM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);